package adminfree.constants;

/**
 *
 * Clase constante que contiene los DML Y DDL para el modulo de Correspondencia
 *
 * @author Carlos Andres Diaz
 *
 */
public class SQLCorrespondencia {

	/** SQL para obtener el detalle de una nomenclatura*/
	public static final String GET_DTL_NOMENCLATURA = "SELECT N.ID_NOMENCLATURA, N.NOMENCLATURA, N.DESCRIPCION, N.CONSECUTIVO_INICIAL, (SELECT NS.SECUENCIA FROM NOMENCLATURAS_SECUENCIA NS WHERE NS.NOMENCLATURA = N.ID_NOMENCLATURA AND NS.ANIO=?1) AS CANT, CE.ID_CAMPO, CE.NOMBRE, CE.DESCRIPCION, CE.TIPO_CAMPO FROM NOMENCLATURAS N LEFT JOIN NOMENCLATURAS_CAMPOS_ENTRADA NC ON(NC.NOMENCLATURA = N.ID_NOMENCLATURA) LEFT JOIN CAMPOS_ENTRADA CE ON(CE.ID_CAMPO = NC.CAMPO) WHERE N.ID_NOMENCLATURA =?";
}
