package adminfree.constants;

/**
 *
 * Clase constante que contiene los DML Y DDL para el modulo de Correspondencia
 *
 * @author Carlos Andres Diaz
 *
 */
public class SQLCorrespondencia {

	/** SQL para obtener el detalle de una nomenclatura*/
	public static final String GET_DTL_NOMENCLATURA = "SELECT N.ID_NOMENCLATURA, N.NOMENCLATURA, N.DESCRIPCION, N.CONSECUTIVO_INICIAL, (SELECT NS.SECUENCIA FROM NOMENCLATURAS_SECUENCIA NS WHERE NS.NOMENCLATURA = N.ID_NOMENCLATURA AND NS.ANIO='?1') AS CANT FROM NOMENCLATURAS N WHERE N.ID_NOMENCLATURA =?";

	/** SQL para obtener el detalle de los campos asociados a una nomenclatura*/
	public static final String GET_DTL_NOMENCLATURA_CAMPOS = "SELECT CE.ID_CAMPO, CE.NOMBRE, CE.DESCRIPCION, CE.TIPO_CAMPO, GROUP_CONCAT(CER.RESTRICCION SEPARATOR ';') AS RESTRICCIONES FROM NOMENCLATURAS_CAMPOS_ENTRADA NCE JOIN CAMPOS_ENTRADA CE ON(CE.ID_CAMPO = NCE.CAMPO) LEFT JOIN CAMPOS_ENTRADA_RESTRICCIONES CER ON(CER.CAMPO = CE.ID_CAMPO) WHERE NCE.NOMENCLATURA=? GROUP BY CE.ID_CAMPO, CE.NOMBRE, CE.DESCRIPCION, CE.TIPO_CAMPO, NCE.ORDEN ORDER BY NCE.ORDEN";
}
